// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System_uznawania_przychodow.Data;

#nullable disable

namespace System_uznawania_przychodow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615200212_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "ul. Kowalska 1, Warszawa",
                            Email = "jan.kowalski@gmail.com",
                            Phone = "500600700"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "ul. Nowaka 5, Kraków",
                            Email = "anna.nowak@gmail.com",
                            Phone = "501601701"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "ul. Wiśniewska 3, Gdańsk",
                            Email = "piotr.wisniewski@gmail.com",
                            Phone = "502602702"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "ul. Wójcika 7, Poznań",
                            Email = "maria.wojcik@gmail.com",
                            Phone = "503603703"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "ul. Kamińska 9, Wrocław",
                            Email = "tomasz.kaminski@gmail.com",
                            Phone = "504604704"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "ul. Firmowa 1, Warszawa",
                            Email = "kontakt@abcsp.pl",
                            Phone = "600700800"
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "ul. Biznesowa 2, Kraków",
                            Email = "biuro@xyzsa.pl",
                            Phone = "601701801"
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "ul. Handlowa 3, Gdańsk",
                            Email = "office@techsolutions.pl",
                            Phone = "602702802"
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "ul. Przemysłowa 4, Poznań",
                            Email = "info@megacorp.pl",
                            Phone = "603703803"
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "ul. Korporacyjna 5, Wrocław",
                            Email = "kontakt@globaltech.pl",
                            Phone = "604704804"
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.CompanyClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClientId");

                    b.ToTable("Company_Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 6,
                            CompanyName = "ABC Sp. z o.o.",
                            Krs = "0000123456"
                        },
                        new
                        {
                            ClientId = 7,
                            CompanyName = "XYZ S.A.",
                            Krs = "0000234567"
                        },
                        new
                        {
                            ClientId = 8,
                            CompanyName = "Tech Solutions Sp. z o.o.",
                            Krs = "0000345678"
                        },
                        new
                        {
                            ClientId = 9,
                            CompanyName = "MegaCorp S.A.",
                            Krs = "0000456789"
                        },
                        new
                        {
                            ClientId = 10,
                            CompanyName = "GlobalTech Sp. z o.o.",
                            Krs = "0000567890"
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.IndividualClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ClientId");

                    b.ToTable("Individual_Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            FirstName = "Jan",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            Pesel = "90010112345"
                        },
                        new
                        {
                            ClientId = 2,
                            FirstName = "Anna",
                            IsDeleted = false,
                            LastName = "Nowak",
                            Pesel = "85020223456"
                        },
                        new
                        {
                            ClientId = 3,
                            FirstName = "Piotr",
                            IsDeleted = false,
                            LastName = "Wiśniewski",
                            Pesel = "78030334567"
                        },
                        new
                        {
                            ClientId = 4,
                            FirstName = "Maria",
                            IsDeleted = false,
                            LastName = "Wójcik",
                            Pesel = "92040445678"
                        },
                        new
                        {
                            ClientId = 5,
                            FirstName = "Tomasz",
                            IsDeleted = false,
                            LastName = "Kamiński",
                            Pesel = "88050556789"
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.CompanyClient", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Client", "Client")
                        .WithOne("CompanyClient")
                        .HasForeignKey("System_uznawania_przychodow.Entities.CompanyClient", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.IndividualClient", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Client", "Client")
                        .WithOne("IndividualClient")
                        .HasForeignKey("System_uznawania_przychodow.Entities.IndividualClient", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Client", b =>
                {
                    b.Navigation("CompanyClient");

                    b.Navigation("IndividualClient");
                });
#pragma warning restore 612, 618
        }
    }
}
