// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System_uznawania_przychodow.Data;

#nullable disable

namespace System_uznawania_przychodow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616160344_Initv7")]
    partial class Initv7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "ul. Kowalska 1, Warszawa",
                            Email = "jan.kowalski@gmail.com",
                            IsDeleted = false,
                            Phone = "500600700"
                        },
                        new
                        {
                            ClientId = 2,
                            Address = "ul. Nowaka 5, Kraków",
                            Email = "anna.nowak@gmail.com",
                            IsDeleted = false,
                            Phone = "501601701"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "ul. Wiśniewska 3, Gdańsk",
                            Email = "piotr.wisniewski@gmail.com",
                            IsDeleted = false,
                            Phone = "502602702"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "ul. Wójcika 7, Poznań",
                            Email = "maria.wojcik@gmail.com",
                            IsDeleted = false,
                            Phone = "503603703"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "ul. Kamińska 9, Wrocław",
                            Email = "tomasz.kaminski@gmail.com",
                            IsDeleted = false,
                            Phone = "504604704"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "ul. Firmowa 1, Warszawa",
                            Email = "kontakt@abcsp.pl",
                            IsDeleted = false,
                            Phone = "600700800"
                        },
                        new
                        {
                            ClientId = 7,
                            Address = "ul. Biznesowa 2, Kraków",
                            Email = "biuro@xyzsa.pl",
                            IsDeleted = false,
                            Phone = "601701801"
                        },
                        new
                        {
                            ClientId = 8,
                            Address = "ul. Handlowa 3, Gdańsk",
                            Email = "office@techsolutions.pl",
                            IsDeleted = false,
                            Phone = "602702802"
                        },
                        new
                        {
                            ClientId = 9,
                            Address = "ul. Przemysłowa 4, Poznań",
                            Email = "info@megacorp.pl",
                            IsDeleted = false,
                            Phone = "603703803"
                        },
                        new
                        {
                            ClientId = 10,
                            Address = "ul. Korporacyjna 5, Wrocław",
                            Email = "kontakt@globaltech.pl",
                            IsDeleted = false,
                            Phone = "604704804"
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.CompanyClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ClientId");

                    b.ToTable("Company_Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 6,
                            CompanyName = "ABC Sp. z o.o.",
                            Krs = "0000123456"
                        },
                        new
                        {
                            ClientId = 7,
                            CompanyName = "XYZ S.A.",
                            Krs = "0000234567"
                        },
                        new
                        {
                            ClientId = 8,
                            CompanyName = "Tech Solutions Sp. z o.o.",
                            Krs = "0000345678"
                        },
                        new
                        {
                            ClientId = 9,
                            CompanyName = "MegaCorp S.A.",
                            Krs = "0000456789"
                        },
                        new
                        {
                            ClientId = 10,
                            CompanyName = "GlobalTech Sp. z o.o.",
                            Krs = "0000567890"
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("SupportYears")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.ContractPayment", b =>
                {
                    b.Property<int>("ContractPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractPaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.HasKey("ContractPaymentId");

                    b.HasIndex("ContractId");

                    b.ToTable("ContractPayments");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            EndDate = new DateOnly(2026, 11, 30),
                            Name = "Black Friday",
                            StartDate = new DateOnly(2026, 11, 23),
                            Value = 15.00m
                        },
                        new
                        {
                            DiscountId = 2,
                            EndDate = new DateOnly(2026, 12, 2),
                            Name = "Cyber Monday",
                            StartDate = new DateOnly(2026, 11, 30),
                            Value = 20.00m
                        },
                        new
                        {
                            DiscountId = 3,
                            EndDate = new DateOnly(2026, 5, 31),
                            Name = "Wiosenna Promocja",
                            StartDate = new DateOnly(2026, 3, 1),
                            Value = 10.00m
                        },
                        new
                        {
                            DiscountId = 4,
                            EndDate = new DateOnly(2026, 8, 31),
                            Name = "Niezwykłe rabaty",
                            StartDate = new DateOnly(2026, 6, 1),
                            Value = 17.50m
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.IndividualClient", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ClientId");

                    b.ToTable("Individual_Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Pesel = "90010112345"
                        },
                        new
                        {
                            ClientId = 2,
                            FirstName = "Anna",
                            LastName = "Nowak",
                            Pesel = "85020223456"
                        },
                        new
                        {
                            ClientId = 3,
                            FirstName = "Piotr",
                            LastName = "Wiśniewski",
                            Pesel = "78030334567"
                        },
                        new
                        {
                            ClientId = 4,
                            FirstName = "Maria",
                            LastName = "Wójcik",
                            Pesel = "92040445678"
                        },
                        new
                        {
                            ClientId = 5,
                            FirstName = "Tomasz",
                            LastName = "Kamiński",
                            Pesel = "88050556789"
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Software", b =>
                {
                    b.Property<int>("SoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("SoftwareId");

                    b.ToTable("Softwares", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            Category = "Finanse",
                            CurrentVersion = "3.2.1",
                            Description = "System do zarządzania finansami",
                            Name = "FinanSoft",
                            Price = 5000.00m
                        },
                        new
                        {
                            SoftwareId = 2,
                            Category = "Edukacja",
                            CurrentVersion = "2.0.5",
                            Description = "Platforma e-learningowa",
                            Name = "EduPlatform",
                            Price = 3500.00m
                        },
                        new
                        {
                            SoftwareId = 3,
                            Category = "HR",
                            CurrentVersion = "4.1.0",
                            Description = "System do zarządzania HR",
                            Name = "HRManager",
                            Price = 7000.00m
                        },
                        new
                        {
                            SoftwareId = 4,
                            Category = "Logistyka",
                            CurrentVersion = "1.8.3",
                            Description = "Magazyn i logistyka",
                            Name = "WarehousePro",
                            Price = 8500.00m
                        },
                        new
                        {
                            SoftwareId = 5,
                            Category = "Sprzedaż",
                            CurrentVersion = "5.0.0",
                            Description = "System CRM",
                            Name = "CRM Master",
                            Price = 4200.00m
                        },
                        new
                        {
                            SoftwareId = 6,
                            Category = "Finanse",
                            CurrentVersion = "2.3.7",
                            Description = "Księgowość",
                            Name = "AccountKeeper",
                            Price = 2000.00m
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.SoftwareDiscount", b =>
                {
                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.HasKey("SoftwareId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("Software_Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            DiscountId = 3
                        },
                        new
                        {
                            SoftwareId = 1,
                            DiscountId = 4
                        },
                        new
                        {
                            SoftwareId = 1,
                            DiscountId = 1
                        },
                        new
                        {
                            SoftwareId = 2,
                            DiscountId = 3
                        },
                        new
                        {
                            SoftwareId = 2,
                            DiscountId = 2
                        },
                        new
                        {
                            SoftwareId = 3,
                            DiscountId = 4
                        });
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.CompanyClient", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Client", "Client")
                        .WithOne("CompanyClient")
                        .HasForeignKey("System_uznawania_przychodow.Entities.CompanyClient", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Contract", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_uznawania_przychodow.Entities.Software", "Software")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.ContractPayment", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.IndividualClient", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Client", "Client")
                        .WithOne("IndividualClient")
                        .HasForeignKey("System_uznawania_przychodow.Entities.IndividualClient", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.SoftwareDiscount", b =>
                {
                    b.HasOne("System_uznawania_przychodow.Entities.Discount", "Discount")
                        .WithMany("SoftwareDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("System_uznawania_przychodow.Entities.Software", "Software")
                        .WithMany("SoftwareDiscounts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Client", b =>
                {
                    b.Navigation("CompanyClient");

                    b.Navigation("Contracts");

                    b.Navigation("IndividualClient");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Discount", b =>
                {
                    b.Navigation("SoftwareDiscounts");
                });

            modelBuilder.Entity("System_uznawania_przychodow.Entities.Software", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("SoftwareDiscounts");
                });
#pragma warning restore 612, 618
        }
    }
}
